### ISSUE TITLE
Spider 的疑问

### ISSUE THREAD

**Issue by supernewtom** [howie6879/talonspider#2]
关于 Spider

如果 start_urls 成员数过多(有几千个)，会一直卡住没有数据产生，要怎么解决呢？

**Comment by howie6879** [comment]
请详细描述 卡住是你没有爬取成功么

**Comment by supernewtom** [comment]
就是一直没有log打印出来(特别久)，但是程序又没报错，一直在运行。但是我把那个 start_urls=start_urls[-10:]  这样截短，它就可以正常跑了。

**Comment by howie6879** [comment]
最好把代码放出来看看

**Comment by howie6879** [comment]
估计是在循环构建待爬取url生成器吧
