### ISSUE TITLE
网络访问各种报错，程序中断

### ISSUE THREAD

**Issue by supernewtom** [howie6879/talonspider#3]
程序并发并不高，但是爬取的网址和内容特别多，经常会有各种网络访问错误问题，发生错误就会中断，怎么让它不中断呢？

TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
报了这个错后就会中断。

**Comment by howie6879** [comment]
你可以把具体代码放gist上我看看么？我比较好排查，然后TimeoutError不该是你的目标网页的问题么？

**Comment by supernewtom** [comment]
我现在代码改了。用另一种写法代替就不会了。
我get_item(url=XXX)  ,这样就会出问题。
但是先用spider,获取html,然后再get_item(html=XXX)，这样就没有问题了。

我还遇到另一个问题:
我在linux 上安装了3.6.3的python ,结果会报错，如下:

  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/talonspider/__init__.py", line 2, in <module>
    from .item import Item
  File "/usr/local/lib/python3.6/site-packages/talonspider/item.py", line 4, in <module>
    from lxml import etree
ImportError: /usr/local/lib/python3.6/site-packages/lxml/etree.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _PyErr_FormatFromCause

**Comment by howie6879** [comment]
你 lxml安装成功了么？

**Comment by supernewtom** [comment]
我安装时它提示已经安装了呀。

[root@iZj6cb27exwwfscqwj7zjzZ /]# pip3 install lxml
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/local/lib/python3.6/site-packages
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by howie6879** [comment]
你进入交互环境：
``` python
from lxml import etree
```
会报错么？

**Comment by supernewtom** [comment]
会报错。

**Comment by howie6879** [comment]
说明安装有问题
你参考下这个  

https://stackoverflow.com/questions/13355984/get-errors-when-import-lxml-etree-to-python
http://roderickhodgson.com/blog/2012/10/27/building-python-lxml-on-mac-os-x-10-dot-7/

**Comment by supernewtom** [comment]
我重新安装个ubuntu系统后就没有上述问题了，我能再问个问题么？如下:

File "/usr/local/lib/python3.4/dist-packages/talonspider/downloader.py", line 75, in download
    requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
AttributeError: 'module' object has no attribute 'packages'

**Comment by howie6879** [comment]
这个问题在什么情况下出现的？

**Comment by supernewtom** [comment]
就是用你的框架跑一个脚本出现的。
这个脚本在windows下运行，但是在ubuntu下不行。
我把脚本放网盘，你可以看下:https://pan.baidu.com/s/1pLkhtub

**Comment by supernewtom** [comment]
我的安装的是这个mysql依赖库:
pip3 install mysql-connector==2.1.4

**Comment by howie6879** [comment]
你mysql库安装的问题 与talonspider无关 
运行无错
![image](https://user-images.githubusercontent.com/17047388/33583664-69ebf682-d996-11e7-8fb2-79e877853367.png)
